---

- name: print ufw_enabled
  debug:
    msg: "ufw_enabled: {{ ufw_enabled }}"
  when: ansible_check_mode

- name: Configuring service state
  community.general.ufw:
    state: "{{ 'enabled' if ufw_enabled else 'disabled' }}"
